name: Trendyol Fırsat Botu

on:
  schedule:
    - cron: "*/15 * * * *" # Her 15 dakikada bir otomatik çalışır
  workflow_dispatch: # Elle tetikleme butonu

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Botu Çalıştır
        run: node scraper.js

      - name: Hafızayı Güncelle (Mükerrer Engelleme İçin)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gonderilenler.json
          if ! git diff --cached --quiet; then
            git commit -m "Hafıza güncellendi"
            git push
          else
            echo "Değişiklik olmadığı için commit atlandı."
          fi
